apiVersion: apps/v1
kind: Deployment
metadata:
name: redis-db
labels:
  app: redis-db
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: redis
      image: redis:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 6379
        name: redis

---
apiVersion: v1
kind: Service
metadata:
name: lb
labels:
  app: lb
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: lb
  tier: lb
type: LoadBalancer
